// vue/travel-journal/src/components/AllTripsMap.vue
<script setup>
import { onMounted, ref, watchEffect, toRaw } from 'vue';
import L from 'leaflet';

const props = defineProps({
    trips: {
        type: Array, // Array<Array<Gps>>
        default: () => []
    }
});

const map = ref(null);
const mapContainer = ref(null);

const initial_view_gps = ref([]);

// Watches for changes and rerenders - needed because of map
watchEffect(() => {
    if (mapContainer.value) {
        if (!map.value) {
            // initialize map only once
            map.value = L.map(mapContainer.value).setView(initial_view_gps.value, 5);

            let hue_rotation;

            // create markers
            props.trips.forEach((trip) => {
                console.log("TRIP: ", trip.name, " - ", trip.id);
                let marker;
                hue_rotation = Math.floor(Math.random() * 360);

                // create lines between markers
                for (var i = 0; i < trip.subtrips.length; i++) {
                    if (i < trip.subtrips.length - 1) {
                        L.polygon([
                            trip.subtrips[i].gps,
                            trip.subtrips[i+1].gps,
                        ]).addTo(map.value);
                    }

                    marker = L.marker(trip.subtrips[i].gps).addTo(toRaw(map.value));
                    marker._icon.style.filter = `hue-rotate(${hue_rotation}deg)`;

                    // popup
                    marker.bindPopup("<a href='/trip/" + trip.id + "' class='text-lg'><b>" + trip.name + "</a></b><br><a class='text-lg'>" + trip.subtrips[i].name + "</a>");
                    marker.on('click', onClick);

                    function onClick(e) {
                        var popup = e.target.getPopup();
                        var content = popup.getContent();
                    }
                }
            });

            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map.value);
        }

        // re-render map
        map.value.invalidateSize();
    }
});

onMounted(()=> {
    // gets first not empty subtrip
    props.trips.forEach((trip) => {
        trip.subtrips.forEach((s) => {
            if (initial_view_gps.value.length) {
                return;
            }
            initial_view_gps.value = s.gps;
        });
    });

    if (!initial_view_gps.value.length) {
        initial_view_gps.value = [50.0755, 14.4378]; // default
    }
});

</script>

<template>
    <div v-if="trips.length > 0" ref="mapContainer" class="w-full h-[80vh] mt-4 sm:mt-5 shadow-card-shadow rounded-2xl"></div>
</template>

// react/trip-diary/src/components/AllTripsMap.js
import React, { useEffect, useRef } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

const AllTripsMap = ({ trips }) => {
  const mapContainerRef = useRef(null);
  const mapRef = useRef(null);

  const customIcon = L.icon({
    iconUrl: require('leaflet/dist/images/marker-icon.png'), // nebo použijte vlastní cestu k obrázku
    iconSize: [25, 41], // Velikost ikony
    iconAnchor: [12, 41], // Ukotvení ikony
    popupAnchor: [1, -34], // Posun popupu vzhledem k ikoně
    shadowUrl: require('leaflet/dist/images/marker-shadow.png'), // Stín markeru
    shadowSize: [41, 41], // Velikost stínu
  });

  useEffect(() => {
    if (!mapRef.current) {
      // Inicializace mapy
      mapRef.current = L.map(mapContainerRef.current).setView([50.0755, 14.4378], 5);

      L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      }).addTo(mapRef.current);
    }

    // Vyčištění a překreslení markerů a polygonů
    mapRef.current.eachLayer((layer) => {
      if (layer instanceof L.Marker || layer instanceof L.Polygon) {
        mapRef.current.removeLayer(layer);
      }
    });

    const latLngs = []; // Pole pro uchování souřadnic všech tripů pro fitBounds

    let initialViewSet = false;
    trips.forEach((trip) => {
      let hueRotation = Math.floor(Math.random() * 360);

      trip.subtrips.forEach((subtrip, index) => {
        // Nastavení inicializačního pohledu
        if (!initialViewSet && subtrip.gps) {
          mapRef.current.setView(subtrip.gps, 5); // Nastavení počátečního pohledu na první GPS
          initialViewSet = true;
        }

        // Přidání markeru
        const marker = L.marker(subtrip.gps, { icon: customIcon }).addTo(mapRef.current);
        latLngs.push(subtrip.gps); // Přidání souřadnic do pole pro fitBounds

        // Přidání pop-upu
        marker.bindPopup(
          `<a href='/trip/${trip.id}' class='text-lg'><b>${trip.name}</b></a><br>
          <a class='text-lg'>${subtrip.name}</a>`
        );

        // Klikací akce na marker
        marker.on('click', (e) => {
          const popup = e.target.getPopup();
          const content = popup.getContent();
          console.log('Popup Content:', content);
        });

        // Přidání čar mezi body
        if (index < trip.subtrips.length - 1) {
          const nextGps = trip.subtrips[index + 1].gps;
          L.polygon([subtrip.gps, nextGps]).addTo(mapRef.current);  // Přidání polygonu přímo na mapu
          latLngs.push(nextGps); // Přidání souřadnic pro fitBounds
        }
      });
    });

    // Automatické přizpůsobení mapy tak, aby zobrazovala všechny markery a polygon
    if (latLngs.length > 0) {
      mapRef.current.fitBounds(latLngs); // Nastavení bounds na všechny souřadnice
    }

    // Upraví velikost mapy při změně okna
    mapRef.current.invalidateSize();

    return () => {
      mapRef.current.off(); // Odstraní všechny event listenery
    };
  }, [trips]);

  return (
    <div
      ref={mapContainerRef}
      style={{ width: '100%', height: '80vh', marginTop: '1rem', borderRadius: '16px' }}
    ></div>
  );
};

export default AllTripsMap;
